version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "00:00"
      timezone: "Asia/Baghdad"
    target-branch: "main"
    labels:
      - "dependency"
