name: muslim_data_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: 3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: 2.26.0
  drift_flutter: 0.2.4
  path_provider: 2.1.5
  sqlite3_flutter_libs: 0.5.32
  sqlite3: 2.7.5
  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  drift_dev: 2.26.0
  build_runner: 2.4.15

flutter:
  assets:
    - assets/db/
