name: 'Setup Flutter'
description: 'Setup Flutter with dependencies'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      shell: bash
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
      shell: bash
    - name: Install dependencies
      run: flutter pub get
      shell: bash