name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.10.0
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Run tests
        run: flutter test --concurrency=1
